- src/actionbar/ButtonWithBadge.tsx
> Change SearchOutlined icon for FilterOutilned icon

- src/widgets/base/Selection.tsx
https://user-images.githubusercontent.com/294235/156770394-158af938-e074-4df6-83c8-d634c0a0ec81.mp4
> Allow input for filter in selection

- src/helpers/formHelper.ts
Needs https://github.com/gisce/ooui.js/pull/44
Fixes https://github.com/gisce/webclient/issues/187
> Fix parsing literals on on_change attributes

- src/actionbar/ButtonWithBadge.tsx
- src/actionbar/TreeActionBar.tsx
- src/common/ButtonWithTooltip.tsx
Closes https://github.com/gisce/webclient/issues/213
> Advanced search activated button

- package-lock.json
- package.json
- src/widgets/views/Form.tsx
Fixes bug https://github.com/gisce/webclient
> Fix bug webclient #251

- package-lock.json
- package.json
- src/widgets/views/Form.tsx
Fixes https://github.com/gisce/webclient/issues/253
> Fixes bug #253

- src/stories/Label.stories.tsx
- src/widgets/base/Label.tsx
From https://github.com/gisce/ooui.js/pull/53
> Add new Label props

- src/index.ts
- src/stories/custom/Switch.stories.tsx
- src/widgets/WidgetFactory.tsx
- src/widgets/custom/Switch.tsx
For boolean fields
Depends on https://github.com/gisce/ooui.js/pull/55
> Add Switch widget

- src/stories/custom/Tags.stories.tsx
- src/widgets/custom/MultiCheckbox.tsx
- src/widgets/custom/Tags.tsx
> Fix labels for tag and multicheckbox

- package-lock.json
- package.json
- src/index.ts
- src/stories/custom/CodeEditor.stories.tsx
- src/widgets/WidgetFactory.tsx
- src/widgets/custom/CodeEditor.tsx
- src/widgets/views/Form.tsx
- Afegim el nou paquest [Monaco Editor](https://www.npmjs.com/package/@monaco-editor/react)
- Necessita: https://github.com/gisce/ooui.js/pull/57
> Add CodeEditor widget

- src/index.ts
- src/stories/custom/ButtonGroup.stories.tsx
- src/widgets/WidgetFactory.tsx
- src/widgets/custom/ButtonGroup.tsx
- Necesita https://github.com/gisce/ooui.js/pull/58
> Add widget ButtonGroup

- package-lock.json
- package.json
- src/stories/containers/Notebook.stories.tsx
- src/widgets/containers/Notebook.tsx
- Needs https://github.com/gisce/ooui.js/pull/60
> Allow tabpos

- package-lock.json
- package.json
- src/stories/containers/Notebook.stories.tsx
- src/widgets/containers/Notebook.tsx
- Needs https://github.com/gisce/ooui.js/pull/61
> Add icon to pages

- package-lock.json
- package.json
- src/helpers/iconMapper.ts
- src/stories/Button.stories.tsx
Add support for [Tabler Icons](https://tabler-icons.io/)
- :octocat: https://github.com/tabler/tabler-icons
> Add Tabler Icons support

- npm-shrinkwrap.json
- package.json
- src/actionbar/FormActionBar.tsx
- src/context/ActionViewContext.tsx
- src/views/ActionView.tsx
> Fix bug webclient#324

- npm-shrinkwrap.json
- package.json
- src/widgets/base/MultiSelection.tsx
Fixes [webclient#328](https://github.com/gisce/webclient/issues/328)
> Fix bug webclient#328

- npm-shrinkwrap.json
- package.json
- src/widgets/base/many2one/Many2one.tsx
🎦 [OpenReplay](https://app.openreplay.com/5341/session/7534057106674014)
> Fix when passing an empty string as id

- npm-shrinkwrap.json
- package.json
- src/views/ActionView.tsx
- src/views/RootView.tsx
- src/widgets/views/SearchTree.tsx
Fixes https://github.com/gisce/webclient/issues/337
> Fixes webclient#337

- npm-shrinkwrap.json
- package.json
- src/helpers/treeHelper.ts
- src/widgets/base/one2many/One2manyInput.tsx
Fixes [webclient#336](https://github.com/gisce/webclient/issues/336)
> Fix one2many sorting bug - webclient#336

- npm-shrinkwrap.json
- package.json
- src/context/ContentRootContext.tsx
- src/views/RootView.tsx
- src/widgets/base/one2many/One2manyInput.tsx
- src/widgets/custom/MultiCheckbox.tsx
- src/widgets/custom/Tags.tsx
Fixes https://github.com/gisce/webclient/issues/349
> Hotfix/bug webclient#349

- npm-shrinkwrap.json
- package.json
- src/hooks/useSearch.ts
Fixes https://github.com/gisce/webclient/issues/361
> Fix bug webclient#361

- npm-shrinkwrap.json
- package.json
- src/types/index.ts
- src/views/actionViews/TreeActionView.tsx
Fixes https://github.com/gisce/webclient/issues/360
> Use treeView.toolbar for fixing webclient#360

- npm-shrinkwrap.json
- package.json
- src/views/ActionView.tsx
Related https://github.com/gisce/webclient/issues/366
> Show error when view_ids don't match

- npm-shrinkwrap.json
- package.json
- src/views/ActionView.tsx
Closes https://github.com/gisce/webclient/issues/371
> Fixes bug webclient#371

- npm-shrinkwrap.json
- package.json
- src/context/ContentRootContext.tsx
Fixes https://github.com/gisce/webclient/issues/376
> Fix bug webclient#376

- npm-shrinkwrap.json
- package.json
- src/views/RootView.tsx
- src/widgets/views/Dashboard/Dashboard.tsx
Fixes https://github.com/gisce/webclient/issues/378
> Fixes bug webclient#378

- npm-shrinkwrap.json
- package.json
> Fixes bug webclient #388

- npm-shrinkwrap.json
- package.json
- src/stories/Label.stories.tsx
- src/widgets/base/Label.tsx
- src/widgets/base/many2one/Many2one.tsx
- vite.config.ts
Fixes https://github.com/gisce/webclient/issues/382
> Add label html rendering

- npm-shrinkwrap.json
- package.json
- src/context/ContentRootContext.tsx
- src/types/index.ts
- src/views/RootView.tsx
- src/widgets/base/many2one/Many2one.tsx
- src/widgets/base/one2many/One2manyInput.tsx
- src/widgets/custom/MultiCheckbox.tsx
- src/widgets/custom/Tags.tsx
Fixes https://github.com/gisce/webclient/issues/375
> Apply Hotfix/webclient#375

- npm-shrinkwrap.json
- package.json
- src/widgets/views/Tree.tsx
Fixes https://github.com/gisce/webclient/issues/358
> Improve text tree (webclient #358)

- npm-shrinkwrap.json
- package.json
- src/helpers/formHelper.ts
- src/widgets/views/Form.tsx
Fixes https://github.com/gisce/webclient/issues/394
> Fix bug webclient#394

- npm-shrinkwrap.json
- package.json
- src/widgets/views/Form.tsx
Fixes https://github.com/gisce/webclient/issues/401
> Fix bad conflict resolution

- npm-shrinkwrap.json
- package.json
- src/helpers/treeHelper.ts
- src/widgets/base/ReferenceTree.tsx
- src/widgets/base/many2one/Many2oneTree.tsx
- src/widgets/base/one2many/One2manyInput.tsx
- src/widgets/views/Dashboard/DashboardTree.tsx
- src/widgets/views/SearchTree.tsx
- src/widgets/views/Tree.tsx
Closes https://github.com/gisce/webclient/issues/413
> Fixes bug webclient#413

- npm-shrinkwrap.json
- package.json
- src/widgets/base/one2many/One2manyInput.tsx
> Fix for one2many change view crash 

- npm-shrinkwrap.json
- package.json
Fixes https://github.com/gisce/webclient/issues/412
> Adjust domain value parsing issues

- npm-shrinkwrap.json
- package.json
- src/stories/Separator.stories.tsx
- src/widgets/base/Separator.tsx
Needs https://github.com/gisce/ooui.js/pull/78
```xml
<separator string="General" icon="home" />
```
> Add icon to separator widget

- npm-shrinkwrap.json
- package.json
- src/context/FormContext.tsx
- src/widgets/base/many2one/Many2one.tsx
- src/widgets/views/Form.tsx
Fixes https://github.com/gisce/webclient/issues/462
> Fix many2one change detection

- npm-shrinkwrap.json
- package.json
- src/stories/containers/Group.stories.tsx
- src/ui/Fieldset.tsx
- src/widgets/containers/Group.tsx
Allow group icon
```xml
<group string="General" icon="home" />
```
- https://github.com/gisce/ooui.js/pull/79
> Add suport for group icon

- npm-shrinkwrap.json
- package.json
- src/common/DatePicker.tsx
- src/widgets/views/Tree.tsx
Fixes https://github.com/gisce/webclient/issues/422
> Fix date format for Date and Datetime widgets and tree columns

- npm-shrinkwrap.json
- package.json
Fixes https://github.com/gisce/webclient/issues/479
> Bump ooui version for adding new context parser features (JSON and objects)

- npm-shrinkwrap.json
- package.json
- src/widgets/views/Form.tsx
Rollback fix for issue https://github.com/gisce/webclient/issues/477
> Rollback save before button action

- src/stories/Label.stories.tsx
- src/widgets/base/Label.tsx
Needs https://github.com/gisce/ooui.js/pull/82
> Better Title level size props

- npm-shrinkwrap.json
- package.json
- src/widgets/custom/Markdown.tsx
Add style to show an scroll when content of markdown overflows the size
> Fix markdown overflow

- npm-shrinkwrap.json
- package.json
- src/actionbar/AttachmentsButtonWrapper.tsx
- src/context/ContentRootContext.tsx
Fixes https://github.com/gisce/webclient/issues/497
> Fix action initialview crash

- npm-shrinkwrap.json
- package.json
- src/widgets/custom/ButtonGroup.tsx
- Work with invisible buttons in button group
- Closes https://github.com/gisce/webclient/issues/511
Needs https://github.com/gisce/ooui.js/pull/84
> Work with invisible buttons in buttongroup

- npm-shrinkwrap.json
- package.json
- src/widgets/base/one2many/One2manyInput.tsx
Related https://github.com/gisce/webclient/issues/510
> Fix 2many child widget domain

- npm-shrinkwrap.json
- package.json
- src/stories/custom/Avatar.stories.tsx
- src/stories/views/Tree.stories.jsx
- src/widgets/custom/Avatar.tsx
- src/widgets/views/Tree.tsx
Add Avatar widget
```xml
<field name="user_id" widget="avatar" />
```
> Add Avatar widget

- npm-shrinkwrap.json
- package.json
- src/common/DatePicker.tsx
Fixes https://github.com/gisce/webclient/issues/528
> Fix datepicker datetime issue

- npm-shrinkwrap.json
- package.json
- src/index.ts
- src/stories/Time.stories.tsx
- src/widgets/WidgetFactory.tsx
- src/widgets/base/Time.tsx
- Necessita https://github.com/gisce/ooui.js/pull/86
- Fixes https://github.com/gisce/webclient/issues/541
> Add Time widget

- npm-shrinkwrap.json
- package.json
- src/widgets/base/Text.tsx
Fixes https://github.com/gisce/webclient/issues/534
> Fix textarea height

- npm-shrinkwrap.json
- package.json
- src/helpers/formHelper.ts
- src/widgets/custom/Tag.tsx
- src/widgets/views/Tree.tsx
- Reaprovechamos el `TagInput` para las vistas *Tree*
- Soporte para Many2One
- Se mejora el color del texto según el background con una nueva función
- Si el color no es un predefinido de estado de Antd calcula el color del texto
> Better widget Tag for many2one

- npm-shrinkwrap.json
- package.json
- src/widgets/custom/Tags.tsx
- S'utilitza la funció de textColor pel color de la lletra segons el background
> Use textColor in Tags widget

- src/widgets/modals/FormModal.tsx
- src/widgets/views/Form.tsx
Related https://github.com/gisce/webclient/issues/351
> Improve and fix responsive modal width render

- npm-shrinkwrap.json
- package.json
- src/widgets/base/one2many/One2manyInput.tsx
- src/widgets/views/Tree.tsx
https://github.com/gisce/react-ooui/assets/294235/02ab3944-c605-46a1-86f1-11160345b3a3
- https://github.com/gisce/react-formiga-table/pull/4
> Table readonly

- npm-shrinkwrap.json
- package.json
- src/widgets/views/Form.tsx
Related https://github.com/gisce/webclient/issues/551
> Refresh data after action popup

- npm-shrinkwrap.json
- package.json
- src/widgets/base/Char.tsx
- src/widgets/base/Text.tsx
Solves https://github.com/gisce/webclient/issues/552
> Fix Firefox div onclick translatable issues

- src/ui/GoToResourceModal.tsx
https://github.com/gisce/react-ooui/assets/294235/3e1f5aed-c85c-4a99-9234-766248ffa88f
Closes https://github.com/gisce/webclient/issues/557
> Add focus on input

- npm-shrinkwrap.json
- package.json
Applies https://github.com/gisce/react-formiga-table/pull/10
> Fix background color badge row selected

- npm-shrinkwrap.json
- package.json
- src/widgets/views/Tree.tsx
- We have to solve an issue in the backend, but for now we ensure that the value is text to execute `.replace()` method
> Fix when backend returns an integer on text field

- npm-shrinkwrap.json
- package.json
- src/helpers/formHelper.ts
- src/stories/Utils.stories.tsx
- src/widgets/custom/Tag.tsx
- src/widgets/custom/Tags.tsx
> Better tags colors

- npm-shrinkwrap.json
- package.json
- src/context/ContentRootContext.tsx
- src/helpers/formHelper.ts
- Work with `ir.actions.act_url` and add a new feature to *interpolate* the url with local variables.
- This will allow us to work with custom protocol handlers: 
- https://github.com/gisce/scannerapp/issues/149
> Allow work with ir.actions.act_url actions

- npm-shrinkwrap.json
- package.json
Related: https://github.com/gisce/webclient/issues/569
Depends on: https://github.com/gisce/ooui.js/pull/90
> Update ooui for fixing json parse context issue

- npm-shrinkwrap.json
- package.json
- src/helpers/treeHelper.ts
- src/widgets/views/Tree.tsx
Depends on: https://github.com/gisce/react-formiga-table/pull/14
Related: https://github.com/gisce/webclient/issues/570
> Fix expandable row glitch

- npm-shrinkwrap.json
- package.json
- src/views/actionViews/GraphActionView.tsx
- src/widgets/views/SearchTree.tsx
- src/widgets/views/searchFilter/SearchFilter.tsx
Depends on: https://github.com/gisce/ooui.js/pull/91
Related: https://github.com/gisce/webclient/issues/429
> Use new widget property in fields and ditch form parsing in search fields

- npm-shrinkwrap.json
- package.json
- src/context/ContentRootContext.tsx
Related: https://github.com/gisce/webclient/issues/574
> Fix context merging order

- npm-shrinkwrap.json
- package.json
- src/widgets/views/Form.tsx
Related https://github.com/gisce/webclient/issues/584
> Block form buttons when a button executes and creates a new register

- npm-shrinkwrap.json
- package.json
- src/helpers/iconMapper.ts
- src/stories/dashboard/DashboardGrid.stories.tsx
- src/widgets/views/Graph/GraphIndicator.tsx
> Fix tabler icons in dashboard

- npm-shrinkwrap.json
- package.json
- src/common/SelectAllRecordsRow.tsx
Related https://github.com/gisce/webclient/issues/591
> New select all records mode

- npm-shrinkwrap.json
- package.json
Applies: https://github.com/gisce/ooui.js/pull/92
Related: https://github.com/gisce/webclient/issues/617
> Fix html entities in totaldomain parameter

- npm-shrinkwrap.json
- package.json
- src/tailwind.generated.css
- src/widgets/custom/Markdown.tsx
Fixes https://github.com/gisce/webclient/issues/639
> Fix markdown antd5

- npm-shrinkwrap.json
- package.json
- src/widgets/base/Button.tsx
Fixes https://github.com/gisce/webclient/issues/643
> Disable button while the action is running

- npm-shrinkwrap.json
- package.json
- src/context/ActionViewContext.tsx
- src/locales/ca_ES.tsx
- src/locales/en_US.tsx
- src/locales/es_ES.tsx
- src/stories/ui/GoToResourceModal.stories.tsx
- src/ui/GoToResourceModal.tsx
- src/views/ActionView.tsx
Closes https://github.com/gisce/webclient/issues/568
> Allow Go to resource multiple ids

- npm-shrinkwrap.json
- package.json
- src/actionbar/DropdownButton.tsx
https://github.com/gisce/react-ooui/assets/294235/4bae7ca9-ee4e-493e-bfd3-aadee9603a81
> Allow filter actions

- npm-shrinkwrap.json
- package.json
- src/actionbar/FormActionBar.tsx
Related https://github.com/gisce/webclient/issues/663
> Fix duplicating items and opening from the form view

- npm-shrinkwrap.json
- package.json
- src/actionbar/FormActionBar.tsx
- src/actionbar/TreeActionBar.tsx
- src/hooks/useExport.ts
- src/types/index.ts
Related https://github.com/gisce/webclient/issues/666
> Add context to unlink method

- npm-shrinkwrap.json
- package.json
- src/common/Field.tsx
- src/stories/Char.stories.tsx
Closes https://github.com/gisce/webclient/issues/673
> Add Inline tooltip

- npm-shrinkwrap.json
- package.json
- src/actionbar/FormActionBar.tsx
Related https://github.com/gisce/webclient/issues/696
> Adjust attachment tree to create new items using proper object linking

- npm-shrinkwrap.json
- package.json
- src/actionbar/DropdownButton.tsx
Closes https://github.com/gisce/webclient/issues/678
Closes https://github.com/gisce/webclient/issues/662
https://github.com/gisce/react-ooui/assets/294235/04c5482c-0001-41bf-90c7-e04f78a01d14
> Fem que tingui una alçada màxima de 300px

- package-lock.json
- package.json
- src/helpers/treeHelper.ts
- src/helpers/treeHelper.tsx
- src/index.ts
- src/ui/TitleHeader.tsx
- src/widgets/modals/FormModal.tsx
- src/widgets/views/Dashboard/DashboardTree.tsx
- src/widgets/views/Graph/GraphDefaults.ts
- src/widgets/views/SearchTree.tsx
- src/widgets/views/Tree/Tree.tsx
- src/widgets/views/Tree/index.ts
- src/widgets/views/Tree/treeComponents.tsx
Closes https://github.com/gisce/webclient/issues/717
> feat: add tree improvements, performance and fix few bugs

- npm-shrinkwrap.json
- package.json
- src/widgets/views/Graph/GraphChart.tsx
Fixes https://github.com/gisce/webclient/issues/734
> Fix graphdefaults issues

- npm-shrinkwrap.json
- package.json
- src/widgets/base/many2one/Many2oneSuffix.tsx
Fixes https://github.com/gisce/webclient/issues/747
Fixes https://github.com/gisce/webclient/issues/746
> Remove duplicates many2onesuffix fields and fixes attrparser for selections
